### PR TITLE
Added shadertoy into rendertexture example. Added perlin noise texture.

### PR DESCRIPTION
**Pull request by Excaa**
As the title says. Not the most optimal way of doing things but really simple for many use cases.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
I'm ok to merge it, but we have one problem: fragment shader here is actually essential part of example.   Can you put it into string quoted by `` instead , please?

**Comment by Excaa** [comment]
Yep, will do that tomorrow morning.

**Comment by ivanpopelyshev** [comment]
OK, I'll merge it but then I move this thing away to mesh&shaders and make mesh-based demo. Filter is overkill for this thing, it uses extra framebuffer for that perlin noise.

Or maybe I copy it across the sections and add it to filters too.

**Comment by Excaa** [comment]
I can make a mesh example from that also. The point of the filterbased was that it's the simplest possible way to do that, not very efficient though. I can do it later today (in about 7 hours time)

**Comment by ivanpopelyshev** [comment]
OK, you understand why I want to get maximum from this ;) Later when we have better multi-file playground we'll move fragment to separate file of course.

**Comment by Excaa** [comment]
Yep, always good to show the correct way how to do things and the easy way :) Should actually add a description to the filter/rt based approach that this should be used only in places where rendering is not constant and that a mesh + rt would be better in those cases as well.

**Pull request merged**
