### PR TITLE
Fix number going to infinity

### PR DESCRIPTION
**Pull request by rohanrhu**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
That will become a problem only after 2^54 frames, which is.. 9 million years? I've calculated that some counters will break in pixi after 3 years of bunnymark :) But not in that case

**Comment by ivanpopelyshev** [comment]
I understand your concern about "far lands", I've hit them multiple times in my games.

**Review by ivanpopelyshev — CHANGES_REQUESTED** [review]
9 million years, buddy. Ok, nay be things will start getting a bit weird in 100k years, but anyway!

**Comment by ivanpopelyshev** [comment]
```
bunny.rotation += 0.1 * delta;
bunny.rotation %= Math.PI * 2;
```

or 

```
bunny.rotation = (bunny.rotation + 0.1 * delta) % (Math.PI * 2);
```

**Comment by rohanrhu** [comment]
I commited again (https://github.com/pixijs/examples/pull/27/commits/11c3c64499ea40958874ac85a0cd4bc71786a746)
This is more correct.. I think blocking number to going infinity is more elegant way :D

**Comment by rohanrhu** [comment]
Yes `bunny.rotation = (bunny.rotation + 0.1 * delta) % (Math.PI * 2);` is good :)

**Comment by rohanrhu** [comment]
and i wonder now about do v8 or other engines calculate (Math.PI*2) for everytime in runtime or calculate and place some static things like these for one time in compiling script to bytecode.. :D

**Comment by ivanpopelyshev** [comment]
I swear, we'll switch to degress, there's no sense in using rads in rotations.

**Comment by rohanrhu** [comment]
I mean multiplication in `Math.PI*2`. Probably runtime multiplies Math.PI and 2 everytime because Math.PI maybe changed but I think it calculate and place some expressions like `60*60*5` or there is "const" in ES6, JS engines maybe optimized for this like `const foo = 5; ..foo*5`...

I care so unnecessary things.

**Pull request closed without merging**
