### PR TITLE
Change maggot to doge

### LINKED ISSUE #145: Please change another sprite in demo Particle Container!
Maggots are so terrible 😭😭😭😭😭

### PR DESCRIPTION
**Pull request by StreakingMan**
Resolve #145

Recently I am learning Pixijs, and I was scared by the maggots again while reading examples 😭😭😭😭😭.I made a pixi-doge picture to replace maggot, its...cuter...I'm sure.

Thanks for the wonderful engine anyway!

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
No need to change CSS files. As for doge, does it have almost same size?

**Comment by bigtimebuddy** [comment]
I'm on-board with changing the maggots, but this looks chaotic. It would be nice to do something that's actually realistic-ish that people could use, modify, or understand how it might be helpful for other applications. A bunch of doge illustrations floating around isn't that useful, IMO. An alternative idea that comes to mind would be a bunch of balloons (maybe with different tints). 

Screen Shot 2022-08-11 at 12 54 17 PM

**Comment by jonlepage** [comment]
i ask MJ about cute,abstract,particule bunny :)
image

**Comment by bigtimebuddy** [comment]
Thanks for the PR, but I'm going to close this since I don't think it's a big improvement. I'd gladly welcome other ideas that have more utility. It shouldn't just be _cute_, it should be foremost _helpful_.

**Pull request closed without merging**
