### PR TITLE
New Example: Filter mask.

### PR DESCRIPTION
**Pull request by rtalon83**
### Description of change

Added new example to show how make mask with filters.

### CODE REVIEW

**Review by ivanpopelyshev — APPROVED** [review]

**Comment by ivanpopelyshev** [comment]
Yep, we need that. too many questions about it

**Comment by bigtimebuddy** [comment]
I think this is a good example @rtalon83. I added a few tweaks for readability, which was easier than leaving a ton of tiny comments: https://pixiplayground.com/#/edit/Mfv0CSXsS9Ew0HVCZsnJD

**Comment by rtalon83** [comment]
Perfect!

**Review by bigtimebuddy — APPROVED** [review]

**Comment by rtalon83** [comment]
I'm crazy about performance. When I work in actionscript3, mult is better than div. For this reason I write ` value * 0.5` instead of `value / 2`

Thanks @bigtimebuddy  @ivanpopelyshev

**Review by themoonrat — APPROVED** [review]

**Comment by themoonrat** [comment]
FYI: After I merge, I'll do a little re-organise and rename and create a new 'Masking' main category with
masking-sprite-alpha.js
masking-graphics.js
and you're one, masking-filter.js

Now developers can see all the available masking options and see which one best fits for them :)

Thanks for the new example!

**Pull request merged**
