### PR TITLE
fix projection examples

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
add projection plugin back

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Where's the 1.0.0 tag on https://github.com/pixijs/pixi-projection?

**Comment by bigtimebuddy** [comment]
@ivanpopelyshev can you please `git push --tags` on your local pixi-projection repo?

**Comment by ivanpopelyshev** [comment]
done

**Comment by bigtimebuddy** [comment]
We've decided to archive this repo. Changes or additions to examples can be made over here:
https://github.com/pixijs/pixijs.com/tree/main/src/data/examples

**Pull request closed without merging**
