### PR TITLE
Dev dat.gui

### PR DESCRIPTION
**Pull request by jonlepage**
Allow the addition of dat.gui when some demo allow.
The idea behind is mainly to make the content more playful and experiment with different feature relate to the demo very quickly.

I will also have an example `spine-events` in mind, I would like to allow the use of datgui.

image

demo you want use dat.gui, just need add as plugin in manifest.json.
image

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
I don't think dat.gui is appropriate in the examples. It over-complicates things and the code is already updatable. I don't think dat.gui adds any additional clarity about how things work and can create a tension of state if things are being animated. Yet, there may be another tool we could create (outside of examples) that could provide users the ability to build a scene interactively. In that case, this plugin might make sense.

**Comment by ivanpopelyshev** [comment]
Actually I think its ok , just not in our current examples, in another section, we need more super-interactive demos.

**Comment by bigtimebuddy** [comment]
This adds it to basic container example

**Comment by ivanpopelyshev** [comment]
Exactly, we need it separate in another section.

**Comment by jonlepage** [comment]
I understand your point guys, no problem with, and you can close the suggest if you want.
But i just want say it not `over-complicates things`!
On the contrary, it makes some demo more understandable.
Basic container example is not good , it was add just for test and show, i can easily remove the commit.

But in background, we can add it only for demo need this to understand all aspects.
Example, for `blending,camera2d3d,mask,filters,heaven,normals,layers...`
It remains optional for just some demo.

From my beginner's point of view, the programming is not my job and am a noobs, I can assure you that some demos have given me a headache, and once in codepen with the possibility to manage the variable and all aspect with `dat.gui`, I have quickly more understood how it worked.

Maybe it because am noobs in dev , but i found this kind of tool very helpful for understand demo features.

**Pull request closed without merging**
