### PR TITLE
Modernizing

### PR DESCRIPTION
**Pull request by themoonrat**
Not changed any of the functionality, but all packages use are brought up to date, moved files around for a better folder layout, brought in a basic build process that makes sense, jigged some css to use space better, and made it so that any plugins used show up above the code example.

After this is accepted, the next step will be bringing the examples up to v5 standards (which may mean updating pixi-legacy), moving them to better categories, and then write some more.

### CODE REVIEW

**Comment by bigtimebuddy** [comment]
Awesome work. I’ve been thinking about similar things for awhile. These are much needed changes. 

Two other ideas (we can do these later):
* might be nice to create a deployment script (could happen on Travis) that’s deploys to a ghpages branch. I don’t like storing min dependencies in here.
* we need a better warning and compatibility for tests, some don’t work in v4, we should provide a clear message that isn’t just an inline comment.

**Review by ivanpopelyshev — APPROVED** [review]

**Review by bigtimebuddy — APPROVED** [review]

**Comment by bigtimebuddy** [comment]
This change will break pixiplayground.com default code because of a link to the bunny, should also make a PR there.

**Comment by ivanpopelyshev** [comment]
Maybe dont change that name? We'll have `pixijs.io/examples/examples/assets` instead of `pixijs.io/examples/required/assets` ,  right?

**Comment by themoonrat** [comment]
There's an npm package that lets you take the dest of a build process on master and have that as the root of the ghpages. That could effect URLs further, so I think I'd like to look into that first, maybe get onto webpack, and then see where we are on URLs.

@englercj could pixiplaygrounds couldn't host its own bunny / small repo of test assets so that there isn't this external dependency on how the examples are laid out?

**Comment by ivanpopelyshev** [comment]
Is there a way to leave a link for old resources (required/assets)?

**Comment by englercj** [comment]
> @englercj could pixiplaygrounds couldn't host its own bunny / small repo of test assets so that there isn't this external dependency on how the examples are laid out?

Absolutely, but that won't affect playgrounds that people have made in the past that link to whatever they link to. Changing the default is easy, changing everyone's existing playground to point elsewhere is not as easy (and I'm not sure if I should?).

**Comment by themoonrat** [comment]
> Two other ideas (we can do these later):
> 
> * might be nice to create a deployment script (could happen on Travis) that’s deploys to a ghpages branch. I don’t like storing min dependencies in here.
> * we need a better warning and compatibility for tests, some don’t work in v4, we should provide a clear message that isn’t just an inline comment.
I've done the second of these. Once I've gone through tidying up the tests, we can add compatibility rules to them.
I know how to do the first, but if we get this version in then I can look at that later.

Cleaned up the code a little to make it clearer what the variables names are doing. Had to jig around to force reloading of the frame anyway due to how I've implemented examples requiring certain pixi versions.

I've added back the 'bunny' asset to the location as expected by pixi playground, but kept everything else in it's new location. I can't just move them all to the old folder, as I've renamed a lot of them for clarity as to where they belong. I'd recommend for the future that pixiplayground points to it's own bunny by default for the future to avoid any dependencies on examples here.

On the to-do list also is to limit how many versions are shown in the drop down list. There's so many it goes off the screen..... 
1. Do we really need to have examples work for v3 now? current version and current version - 1 sounds reasonable to me. Can't anyone wanting to find out how to start making things in v3 these days....
2. How about limiting v4 versions to only show the latest 'patch' version from each minor branch? So 4.0.3, 4.1.1, 4.2.3 etc?

**Comment by themoonrat** [comment]
@bigtimebuddy Ping to have another quick look and merge if you're ok

**Comment by ivanpopelyshev** [comment]
1. v4 is enough.
2. we dont need anything below 4.8

**Comment by ivanpopelyshev** [comment]
I'll make compatibility layer like i did for v3, `pixi-legacy`. The idea is to use V5 packages and names on top V4 , that way we wont have to provide code compatible with V4 in all examples.

**Comment by englercj** [comment]
Honestly if we have the last 2-3 minor versions of any major version available that is probably sufficient.

**Comment by englercj** [comment]
I've merged @themoonrat's PR to pixi-playground which updates the default url as well as running through the DB and updating the old URL string to the new one.

**Pull request merged**
