### PR TITLE
Added DragonBones examples with PIXI 5.0

### PR DESCRIPTION
**Pull request by rtalon83**
I have added two dragonBones examples compatible with PIXI 5.0.

- Robot (simple armature animation)
- Eye Tracking (Mesh)

Added: pixi-dragonbones runtime PIXI 5.0 + dragonBones 5.7 (lastest)

### CODE REVIEW

**Comment by themoonrat** [comment]
Could you run the lint command over this please?

**Comment by ivanpopelyshev** [comment]
I'm gonna set up it somewhere in pixijs namespace soon

**Review by themoonrat — APPROVED** [review]

**Comment by rtalon83** [comment]
More information about pixi-dragonbones Plugin:

- DB Fork: https://github.com/rtalon83/DragonBonesJS
- Pull Request (master DB): https://github.com/DragonBones/DragonBonesJS/pull/103

- `pixi.js-legacy.d.ts` was created from official pixi.js github: `npm run types`

**Comment by themoonrat** [comment]
I'll give them a little time to at least comment on your PR. If there's slower progress on that, then I'll merge in with a comment at the top of your example pointing people to your version of the dragonbones repo

**Comment by rtalon83** [comment]
I agree with you @themoonrat 

Examples added:
https://rtalon83.github.io/examples/#/plugin-dragonbones/robot.js
https://rtalon83.github.io/examples/#/plugin-dragonbones/eyetracking.js

**Comment by rtalon83** [comment]
There is not a lot action out in dragonbones git. I think the best 2d animation nowadays is Spine, no?
Is there any dragonbones similar project?

**Comment by jonlepage** [comment]
i know it existe a dragonbone plugin for rmmv , and rmmv use pixijs.
i never take a look but here.
https://forums.rpgmakerweb.com/index.php?threads/rmmv-dragonbones-2d-animation-integration.81027/

**Pull request merged**
